[misc]
# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["system", "tmux", "npm", "pnpm", "vim", "yarn", "containers"]

# Ignore failures for these steps
ignore_failures = ["git"]

[git]
# Additional git repositories to pull
repos = [
    "~/.tmux/",
]

# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"

