[misc]
# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["system", "tmux", "node", "pnpm", "vim", "yarn", "containers", "uv", "pyenv"]

# Ignore failures for these steps
ignore_failures = ["git_repos"]

[git]
# Additional git repositories to pull
repos = [
    "~/.tmux/",
]

# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"

