enable-ssh-support
ttyname $GPG_TTY

default-cache-ttl 60
max-cache-ttl 120

# for some reason ssh+gpg is not playing well together with curses pinentry
# the GPG_TTY variable is not passed along and it doesn't get a tty to ask for the passphrase
# this wrapper script replaces the option passed to pinentry with the TTY
# and that only works with that extra socket for some reason
pinentry-program $HOME/.gnupg/wrapper.sh
extra-socket /tmp/S.gpg-agent.extra
allow-loopback-pinentry
